name: 'badge-creator'
description: 'This action allows you to make a badge that shows the translation progress of your Crowdin project'
author: 'Globalfun32y439y54'

branding:
  icon: 'bar-chart'
  color: 'gray-dark'

inputs:
  token:
    description: 'Crowdin API Token'
    required: true
  project_id:
    description: 'Crowdin Project ID'
    required: true
  path:  
    description: 'The Path You Want To Save The .svg File To'
    required: false
  language_rename_map:
    description: 'JSON string to rename languages (e.g., {"German": "Deutsch"})'
    required: false
    default: '{}'
  output_path:
    description: 'Directory to save the generated files'
    required: false
    default: './'
  toggledefault:
    description: 'This allows you so show your default language'
    required: false
    default: 'false'
  defaultlanguage:
    description: 'JSON string to default language (e.g., { "name": "English", "progress": 100, "url": "https://crowdin.com/project/bettercanvas" }'
    required: false
    default: '{}'


outputs:
  svg:
    description: 'Generated SVG file content'

runs:
  using: node20
  main: dist/index.js
