name: 'badge-creator'

description: 'This action allows you to make a badge that shows the translation progress of your Crowdin project'

branding:
  icon: 'bar-chart'
  color: 'gray-dark'

inputs:
  token:
    description: 'Crowdin API Token'
    required: true
  project_id:
    description: 'Crowdin Project ID'
    required: true
outputs:
  svg:
    description: 'Generated SVG file content'
runs:
  using: 'docker'
  image: 'Dockerfile'
