name: 'test'

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: badge-creator
        uses: Globalfun32y439y54/github-action@V1.0.11
        with:
            token: ${{ secrets.TOKEN }}
            project_id: ${{ secrets.PROJECT_ID }}
            output_path: ./icon
            language_rename_map: '{ "Chinese Simplified": "Chinese (Simplified, China)", "Chinese Traditional": "Chinese (Simplified, Taiwan)", }'
            toggledefault: true
            defaultlanguage: '{ "name": "English", "progress": 100, "url": "https://crowdin.com/project/bettercanvas", "color": "#2eccaa" }'
